server:
    port: 8080
    servlet:
        context-path: /

spring:
    datasource:
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shoppingMall01?useUnicode=true&characterEncoding=UTF-8

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql : true
                default_batch_fetch_size: 1000
        show-sql: true

logging:
    level:
        org.hibernate.type: trace

jwt:
    secret-key-source: super-coding

