server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${ENDPOINT}:3306/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: ${ACCESS_TOKEN_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_SECONDS}

logging:
  config: classpath:logback-spring.xml